### ISSUE TITLE
the problem

### ISSUE THREAD

**Issue by hsmfbt** [AdityaChaudhary/blueborne_any#1]
.] Doing stack memeory leak...
Traceback (most recent call last):
  File "doit.py", line 203, in <module>
    main(*sys.argv[1:])
  File "doit.py", line 178, in main
    libc_text_base, bluetooth_default_bss_base = memory_leak_get_bases(src, src_hci, dst)
  File "doit.py", line 96, in memory_leak_get_bases
    result = bluedroid.do_sdp_info_leak(dst, src)
  File "/root/Desktop/blueborne_any/android/bluedroid.py", line 13, in do_sdp_info_leak
    socket = btsock.l2cap_connect((dst, SDP_PSM), (src, 0), MIN_MTU)
  File "/root/Desktop/blueborne_any/android/btsock.py", line 25, in l2cap_connect
    sock.connect(dst)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 113] No route to host

**Comment by AdityaChaudhary** [comment]
Can you please post the output of `ifconfig` and the command that you ran.

**Comment by hsmfbt** [comment]
wlan0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.42.0.1  netmask 255.255.255.0  broadcast 10.42.0.255
        inet6 fe80::6d8d:d6a3:6d15:1404  prefixlen 64  scopeid 0x20<link>
        ether 54:35:30:99:6d:af  txqueuelen 1000  (Ethernet)
        RX packets 16460  bytes 2811303 (2.6 MiB)
        RX errors 0  dropped 2  overruns 0  frame 0
        TX packets 19296  bytes 20018012 (19.0 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0






command::: python2 doit.py hci0 18:3A:2D:14:37:B0 10.42.0.1
